# Generated by Django 6.0.6 on 2026-07-20 13:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0005_materialindustryguide_materialpartguide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_hourly_rate', models.PositiveIntegerField(default=100000, verbose_name='نرخ پیش\u200cفرض هر ساعت چاپ به تومان')),
                ('default_labor_percent', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیش\u200cفرض دستمزد')),
                ('minimum_order_amount', models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ سفارش')),
                ('packaging_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه بسته\u200cبندی')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مالیات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات قیمت\u200cگذاری فروشگاه',
                'verbose_name_plural': 'تنظیمات قیمت\u200cگذاری فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='PrintQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=100, verbose_name='نام کیفیت')),
                ('layer_height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ارتفاع لایه میلی\u200cمتر')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کیفیت چاپ',
                'verbose_name_plural': 'کیفیت\u200cهای چاپ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('printing', 'پرینت سه\u200cبعدی'), ('reverse_engineering', 'مهندسی معکوس'), ('automotive', 'قطعات خودرو و موتورسیکلت'), ('home_appliance', 'قطعات لوازم خانگی'), ('model_making', 'ماکت\u200cسازی و پروژه دانشگاهی'), ('kids_drawing', 'تبدیل نقاشی کودک به فیگور'), ('custom_figure', 'فیگور و هدیه شخصی\u200cسازی\u200cشده'), ('industrial', 'قطعات صنعتی')], db_index=True, max_length=40, verbose_name='نوع خدمت')),
                ('title', models.CharField(max_length=220, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=240, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.CharField(max_length=350, verbose_name='توضیح کوتاه')),
                ('content', models.TextField(verbose_name='محتوای کامل')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='store/services/', verbose_name='تصویر اصلی')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='توضیحات سئو')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفحه خدمات سئویی',
                'verbose_name_plural': 'صفحات خدمات سئویی',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('automotive', 'قطعات خودرو'), ('motorcycle', 'قطعات موتورسیکلت'), ('home_appliance', 'قطعات لوازم خانگی'), ('industrial', 'قطعات صنعتی'), ('academic', 'ماکت و پروژه دانشگاهی'), ('creative', 'محصولات خلاقانه و شخصی\u200cسازی'), ('general', 'سایر محصولات')], db_index=True, default='general', max_length=30, verbose_name='بخش اصلی')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, max_length=180, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/categories/', verbose_name='تصویر')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='توضیحات سئو')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته محصول',
                'verbose_name_plural': 'دسته\u200cهای محصولات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=240, unique=True, verbose_name='اسلاگ')),
                ('sku', models.CharField(max_length=80, unique=True, verbose_name='کد محصول')),
                ('short_description', models.CharField(max_length=350, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('main_image', models.ImageField(upload_to='store/products/', verbose_name='تصویر اصلی')),
                ('model_file', models.FileField(blank=True, help_text='این فایل نباید به\u200cصورت عمومی لینک شود.', null=True, upload_to='store/private-models/', verbose_name='فایل سه\u200cبعدی داخلی')),
                ('dimensions', models.CharField(blank=True, max_length=120, verbose_name='ابعاد')),
                ('technical_notes', models.TextField(blank=True, verbose_name='مشخصات و نکات فنی')),
                ('installation_guide', models.TextField(blank=True, verbose_name='راهنمای نصب')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='محصول ویژه')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('view_count', models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='تعداد بازدید')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='توضیحات سئو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول آماده چاپ',
                'verbose_name_plural': 'محصولات آماده چاپ',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن دیدگاه')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دیدگاه محصول',
                'verbose_name_plural': 'دیدگاه\u200cهای محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('vehicle', 'خودرو'), ('motorcycle', 'موتورسیکلت'), ('appliance', 'لوازم خانگی'), ('industrial', 'تجهیزات صنعتی'), ('other', 'سایر')], max_length=20, verbose_name='نوع سازگاری')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='برند')),
                ('model', models.CharField(blank=True, max_length=150, verbose_name='مدل')),
                ('variant', models.CharField(blank=True, max_length=150, verbose_name='تیپ یا نسخه')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='از سال')),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تا سال')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='توضیحات سازگاری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سازگاری محصول',
                'verbose_name_plural': 'سازگاری\u200cهای محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/products/gallery/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=220, verbose_name='متن جایگزین تصویر')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='store.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پسند محصول',
                'verbose_name_plural': 'پسندهای محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('automotive', 'قطعه خودرو'), ('motorcycle', 'قطعه موتورسیکلت'), ('home_appliance', 'قطعه لوازم خانگی'), ('industrial', 'قطعه صنعتی'), ('academic', 'ماکت یا پروژه دانشگاهی'), ('kids_drawing', 'نقاشی کودک به فیگور'), ('custom_figure', 'فیگور سفارشی'), ('other', 'سایر')], db_index=True, max_length=30, verbose_name='نوع درخواست')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='شماره تماس')),
                ('title', models.CharField(max_length=220, verbose_name='عنوان درخواست')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='برند')),
                ('model', models.CharField(blank=True, max_length=150, verbose_name='مدل')),
                ('year', models.CharField(blank=True, max_length=30, verbose_name='سال یا نسخه')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('waiting_sample', 'در انتظار نمونه'), ('modeling', 'در حال طراحی'), ('testing', 'در حال تست'), ('published', 'تبدیل\u200cشده به محصول'), ('rejected', 'رد شده')], db_index=True, default='new', max_length=30, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='store.product', verbose_name='محصول مرتبط')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_product_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست قطعه یا پروژه',
                'verbose_name_plural': 'درخواست\u200cهای قطعه و پروژه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/requests/', verbose_name='تصویر')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productrequest', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'تصویر درخواست',
                'verbose_name_plural': 'تصاویر درخواست',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان نظر')),
                ('body', models.TextField(verbose_name='متن نظر')),
                ('is_verified_purchase', models.BooleanField(db_index=True, default=False, verbose_name='خرید تأییدشده')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر و امتیاز محصول',
                'verbose_name_plural': 'نظرات و امتیازهای محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='کد تنوع')),
                ('material_weight_grams', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن مصرفی متریال به گرم')),
                ('final_weight_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن نهایی محصول به گرم')),
                ('shipping_weight_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن قابل محاسبه برای ارسال به گرم')),
                ('print_time_minutes', models.PositiveIntegerField(verbose_name='زمان چاپ به دقیقه')),
                ('hourly_rate_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='نرخ ساعتی اختصاصی')),
                ('labor_percent_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد دستمزد اختصاصی')),
                ('post_processing_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه پرداخت\u200cکاری')),
                ('fixed_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه ثابت اختصاصی')),
                ('cached_unit_price', models.PositiveIntegerField(db_index=True, default=0, verbose_name='قیمت واحد محاسبه\u200cشده')),
                ('minimum_quantity', models.PositiveIntegerField(default=1, verbose_name='حداقل تعداد')),
                ('maximum_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد')),
                ('stock_status', models.CharField(choices=[('made_to_order', 'تولید پس از سفارش'), ('in_stock', 'آماده ارسال'), ('preorder', 'پیش\u200cسفارش'), ('out_of_stock', 'ناموجود')], db_index=True, default='made_to_order', max_length=20, verbose_name='وضعیت موجودی')),
                ('lead_time_min_days', models.PositiveSmallIntegerField(default=1, verbose_name='حداقل زمان آماده\u200cسازی')),
                ('lead_time_max_days', models.PositiveSmallIntegerField(default=3, verbose_name='حداکثر زمان آماده\u200cسازی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_variants', to='website.material', verbose_name='متریال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='محصول')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='store.printquality', verbose_name='کیفیت چاپ')),
            ],
            options={
                'verbose_name': 'تنوع قابل سفارش محصول',
                'verbose_name_plural': 'تنوع\u200cهای قابل سفارش محصولات',
                'ordering': ['product', 'quality__sort_order', 'material__sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-published_at'], name='store_produ_is_acti_e6c3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='store_produ_categor_591340_idx'),
        ),
        migrations.AddConstraint(
            model_name='productlike',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_store_product_like'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_store_product_review'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'material', 'quality'), name='unique_store_product_material_quality'),
        ),
    ]
