from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import store.models


class Migration(migrations.Migration):
    dependencies = [("store", "0006_location_county_product_schema"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.AddField(model_name="productvariant", name="track_inventory", field=models.BooleanField(default=False, verbose_name="کنترل موجودی عددی")),
        migrations.AddField(model_name="productvariant", name="stock_quantity", field=models.PositiveIntegerField(default=0, verbose_name="موجودی فیزیکی")),
        migrations.AddField(model_name="productvariant", name="reserved_quantity", field=models.PositiveIntegerField(default=0, editable=False, verbose_name="موجودی رزروشده")),
        migrations.AddField(model_name="productvariant", name="low_stock_threshold", field=models.PositiveIntegerField(default=2, verbose_name="آستانه هشدار موجودی")),
        migrations.AddField(model_name="productvariant", name="allow_backorder", field=models.BooleanField(default=False, verbose_name="اجازه سفارش بیشتر از موجودی")),
        migrations.CreateModel(name="Coupon", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("code", models.CharField(db_index=True, max_length=50, unique=True, verbose_name="کد تخفیف")),
            ("title", models.CharField(max_length=150, verbose_name="عنوان")),
            ("discount_type", models.CharField(choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")], default="percent", max_length=20, verbose_name="نوع تخفیف")),
            ("value", models.PositiveBigIntegerField(verbose_name="مقدار تخفیف")),
            ("minimum_order_amount", models.PositiveBigIntegerField(default=0, verbose_name="حداقل مبلغ سفارش")),
            ("maximum_discount", models.PositiveBigIntegerField(default=0, verbose_name="سقف تخفیف؛ صفر یعنی بدون سقف")),
            ("usage_limit", models.PositiveIntegerField(default=0, verbose_name="سقف کل استفاده؛ صفر یعنی نامحدود")),
            ("per_user_limit", models.PositiveIntegerField(default=1, verbose_name="سقف استفاده هر مشتری")),
            ("used_count", models.PositiveIntegerField(default=0, editable=False, verbose_name="تعداد استفاده قطعی")),
            ("starts_at", models.DateTimeField(blank=True, null=True, verbose_name="شروع اعتبار")),
            ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="پایان اعتبار")),
            ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="فعال")),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("categories", models.ManyToManyField(blank=True, related_name="coupons", to="store.category", verbose_name="دسته‌های مجاز")),
            ("products", models.ManyToManyField(blank=True, related_name="coupons", to="store.product", verbose_name="محصولات مجاز")),
        ], options={"verbose_name": "کد تخفیف", "verbose_name_plural": "کدهای تخفیف", "ordering": ["-created_at"]}),
        migrations.AddField(model_name="storeorder", name="county", field=models.CharField(blank=True, max_length=120, verbose_name="شهرستان")),
        migrations.AddField(model_name="storeorder", name="coupon", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="store.coupon", verbose_name="کد تخفیف")),
        migrations.AddField(model_name="storeorder", name="coupon_code", field=models.CharField(blank=True, max_length=50, verbose_name="کد تخفیف هنگام سفارش")),
        migrations.AddField(model_name="storeorder", name="inventory_reserved", field=models.BooleanField(default=False, verbose_name="موجودی رزرو شده")),
        migrations.AddField(model_name="storeorder", name="reservation_expires_at", field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="پایان اعتبار رزرو")),
        migrations.CreateModel(name="CouponUsage", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("discount_amount", models.PositiveBigIntegerField(default=0, verbose_name="مبلغ تخفیف")),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("coupon", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="usages", to="store.coupon", verbose_name="کد تخفیف")),
            ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="coupon_usage", to="store.storeorder", verbose_name="سفارش")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="coupon_usages", to=settings.AUTH_USER_MODEL, verbose_name="مشتری")),
        ], options={"verbose_name": "استفاده از کد تخفیف", "verbose_name_plural": "استفاده‌های کد تخفیف"}),
        migrations.CreateModel(name="InventoryMovement", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("movement_type", models.CharField(choices=[("stock_in", "ورود موجودی"), ("stock_out", "خروج موجودی"), ("reserve", "رزرو سفارش"), ("release", "آزادسازی رزرو"), ("sale", "فروش قطعی"), ("return", "بازگشت کالا"), ("adjustment", "اصلاح دستی")], db_index=True, max_length=20, verbose_name="نوع گردش")),
            ("quantity", models.IntegerField(verbose_name="تعداد تغییر")),
            ("stock_after", models.PositiveIntegerField(default=0, verbose_name="موجودی پس از تغییر")),
            ("reserved_after", models.PositiveIntegerField(default=0, verbose_name="رزرو پس از تغییر")),
            ("note", models.CharField(blank=True, max_length=300, verbose_name="توضیح")),
            ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_actions", to=settings.AUTH_USER_MODEL, verbose_name="ثبت‌کننده")),
            ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_movements", to="store.storeorder", verbose_name="سفارش")),
            ("variant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_movements", to="store.productvariant", verbose_name="تنوع محصول")),
        ], options={"verbose_name": "گردش موجودی", "verbose_name_plural": "گردش‌های موجودی", "ordering": ["-created_at", "-id"]}),
        migrations.CreateModel(name="StoreOrderEvent", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("status", models.CharField(blank=True, max_length=30, verbose_name="وضعیت")),
            ("title", models.CharField(max_length=180, verbose_name="عنوان رویداد")),
            ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ("is_public", models.BooleanField(default=True, verbose_name="قابل نمایش به مشتری")),
            ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="store_order_events", to=settings.AUTH_USER_MODEL, verbose_name="ثبت‌کننده")),
            ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="store.storeorder", verbose_name="سفارش")),
        ], options={"verbose_name": "رویداد سفارش", "verbose_name_plural": "رویدادهای سفارش", "ordering": ["-created_at", "-id"]}),
        migrations.CreateModel(name="Shipment", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("carrier", models.CharField(blank=True, max_length=120, verbose_name="شرکت حمل")),
            ("service_name", models.CharField(blank=True, max_length=120, verbose_name="نوع سرویس")),
            ("tracking_code", models.CharField(blank=True, db_index=True, max_length=120, verbose_name="کد رهگیری")),
            ("tracking_url", models.URLField(blank=True, verbose_name="لینک رهگیری")),
            ("status", models.CharField(choices=[("preparing", "در حال آماده‌سازی"), ("shipped", "تحویل شرکت حمل"), ("delivered", "تحویل مشتری"), ("returned", "مرجوع‌شده")], db_index=True, default="preparing", max_length=20, verbose_name="وضعیت ارسال")),
            ("shipped_at", models.DateTimeField(blank=True, null=True, verbose_name="زمان ارسال")),
            ("estimated_delivery_date", models.DateField(blank=True, null=True, verbose_name="تحویل تخمینی")),
            ("delivered_at", models.DateTimeField(blank=True, null=True, verbose_name="زمان تحویل")),
            ("note", models.TextField(blank=True, verbose_name="توضیحات")),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="shipment", to="store.storeorder", verbose_name="سفارش")),
        ], options={"verbose_name": "مرسوله", "verbose_name_plural": "مرسوله‌ها"}),
        migrations.CreateModel(name="StoreInvoice", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("invoice_number", models.CharField(db_index=True, default=store.models.generate_invoice_number, editable=False, max_length=40, unique=True, verbose_name="شماره فاکتور")),
            ("seller_name", models.CharField(max_length=180, verbose_name="نام فروشنده")),
            ("seller_phone", models.CharField(blank=True, max_length=30, verbose_name="تلفن فروشنده")),
            ("seller_address", models.TextField(blank=True, verbose_name="آدرس فروشنده")),
            ("buyer_name", models.CharField(max_length=180, verbose_name="نام خریدار")),
            ("buyer_phone", models.CharField(max_length=30, verbose_name="تلفن خریدار")),
            ("buyer_address", models.TextField(verbose_name="آدرس خریدار")),
            ("subtotal", models.PositiveBigIntegerField(default=0, verbose_name="جمع کالا")),
            ("discount_amount", models.PositiveBigIntegerField(default=0, verbose_name="تخفیف")),
            ("shipping_fee", models.PositiveBigIntegerField(default=0, verbose_name="هزینه ارسال")),
            ("packaging_fee", models.PositiveBigIntegerField(default=0, verbose_name="هزینه بسته‌بندی")),
            ("tax_amount", models.PositiveBigIntegerField(default=0, verbose_name="مالیات")),
            ("total_amount", models.PositiveBigIntegerField(default=0, verbose_name="مبلغ نهایی")),
            ("issued_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="تاریخ صدور")),
            ("order", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="invoice", to="store.storeorder", verbose_name="سفارش")),
        ], options={"verbose_name": "فاکتور فروش", "verbose_name_plural": "فاکتورهای فروش", "ordering": ["-issued_at"]}),
        migrations.CreateModel(name="CustomerNotification", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("notification_type", models.CharField(choices=[("order", "سفارش"), ("payment", "پرداخت"), ("shipping", "ارسال"), ("system", "سیستمی")], db_index=True, default="system", max_length=20, verbose_name="نوع")),
            ("title", models.CharField(max_length=180, verbose_name="عنوان")),
            ("message", models.TextField(verbose_name="پیام")),
            ("url", models.CharField(blank=True, max_length=500, verbose_name="لینک")),
            ("read_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="زمان مشاهده")),
            ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="store_notifications", to=settings.AUTH_USER_MODEL, verbose_name="مشتری")),
        ], options={"verbose_name": "اعلان مشتری", "verbose_name_plural": "اعلان‌های مشتریان", "ordering": ["-created_at", "-id"]}),
        migrations.CreateModel(name="ReturnRequest", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("reason", models.CharField(choices=[("defect", "ایراد یا شکستگی"), ("wrong_item", "کالای اشتباه"), ("not_as_described", "مغایرت با توضیحات"), ("other", "سایر")], max_length=30, verbose_name="دلیل")),
            ("description", models.TextField(verbose_name="شرح درخواست")),
            ("image", models.ImageField(blank=True, null=True, upload_to="store/returns/", verbose_name="تصویر")),
            ("status", models.CharField(choices=[("submitted", "ثبت‌شده"), ("reviewing", "در حال بررسی"), ("approved", "تأیید مرجوعی"), ("rejected", "ردشده"), ("received", "کالا دریافت شد"), ("refunded", "وجه مسترد شد"), ("closed", "بسته‌شده")], db_index=True, default="submitted", max_length=20, verbose_name="وضعیت")),
            ("admin_response", models.TextField(blank=True, verbose_name="پاسخ مدیریت")),
            ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="return_requests", to="store.storeorderitem", verbose_name="ردیف سفارش")),
            ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="return_requests", to="store.storeorder", verbose_name="سفارش")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="store_return_requests", to=settings.AUTH_USER_MODEL, verbose_name="مشتری")),
        ], options={"verbose_name": "درخواست مرجوعی", "verbose_name_plural": "درخواست‌های مرجوعی", "ordering": ["-created_at"]}),
        migrations.CreateModel(name="ProductFAQ", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("question", models.CharField(max_length=300, verbose_name="سؤال")),
            ("answer", models.TextField(verbose_name="پاسخ")),
            ("sort_order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="فعال")),
            ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="faqs", to="store.product", verbose_name="محصول")),
        ], options={"verbose_name": "پرسش متداول محصول", "verbose_name_plural": "پرسش‌های متداول محصول", "ordering": ["sort_order", "id"]}),
        migrations.CreateModel(
            name="StoreOperationsDashboard",
            fields=[],
            options={"verbose_name": "داشبورد عملیات فروشگاه", "verbose_name_plural": "داشبورد عملیات فروشگاه", "proxy": True, "indexes": [], "constraints": []},
            bases=("store.storeorder",),
        ),
    ]
