# Generated by Django 5.1.7 on 2026-07-20 17:31

import django.db.models.deletion
import store.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_affiliate_tiers(apps, schema_editor):
    Tier = apps.get_model("store", "AffiliateTier")
    Tier.objects.get_or_create(
        slug="default",
        defaults={
            "name": "همکار پایه",
            "commission_type": "percent",
            "commission_value": Decimal("5"),
            "attribution_days": 30,
            "hold_days": 7,
            "minimum_payout": 500000,
            "include_self_orders": False,
            "is_active": True,
        },
    )
    Tier.objects.get_or_create(
        slug="publisher",
        defaults={
            "name": "رسانه و ناشر",
            "commission_type": "percent",
            "commission_value": Decimal("8"),
            "attribution_days": 45,
            "hold_days": 7,
            "minimum_payout": 1000000,
            "include_self_orders": False,
            "is_active": True,
        },
    )
    Tier.objects.get_or_create(
        slug="wholesale",
        defaults={
            "name": "همکار خرید عمده",
            "commission_type": "percent",
            "commission_value": Decimal("3"),
            "attribution_days": 30,
            "hold_days": 3,
            "minimum_payout": 500000,
            "include_self_orders": True,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='عنوان کمپین')),
                ('slug', models.SlugField(allow_unicode=True, max_length=160, verbose_name='شناسه کمپین')),
                ('target_path', models.CharField(default='/', max_length=500, verbose_name='مسیر مقصد داخلی')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کمپین معرف',
                'verbose_name_plural': 'کمپین\u200cهای معرف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام سطح همکاری')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='شناسه')),
                ('commission_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت برای هر سفارش')], default='percent', max_length=20, verbose_name='نوع پورسانت')),
                ('commission_value', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=10, verbose_name='مقدار پورسانت')),
                ('attribution_days', models.PositiveIntegerField(default=30, verbose_name='اعتبار لینک معرفی به روز')),
                ('hold_days', models.PositiveIntegerField(default=7, verbose_name='دوره انتظار تأیید پورسانت پس از تحویل')),
                ('minimum_payout', models.PositiveBigIntegerField(default=500000, verbose_name='حداقل مبلغ تسویه به تومان')),
                ('include_self_orders', models.BooleanField(default=False, verbose_name='محاسبه پاداش خریدهای شخصی همکار')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سطح همکاری',
                'verbose_name_plural': 'سطوح همکاری',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='storeorder',
            name='affiliate_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='کد معرف هنگام سفارش'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='affiliate_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.affiliatecampaign', verbose_name='کمپین معرف'),
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(db_index=True, max_length=64, verbose_name='شناسه ناشناس بازدیدکننده')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='هش IP')),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, verbose_name='هش مرورگر')),
                ('landing_path', models.CharField(blank=True, max_length=500, verbose_name='صفحه ورود')),
                ('referrer_url', models.CharField(blank=True, max_length=500, verbose_name='صفحه ارجاع\u200cدهنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='store.affiliatecampaign', verbose_name='کمپین')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_clicks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر شناسایی\u200cشده')),
            ],
            options={
                'verbose_name': 'کلیک معرفی',
                'verbose_name_plural': 'کلیک\u200cهای معرفی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=True, verbose_name='انتساب دائمی')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیریت')),
                ('attributed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_attribution', to=settings.AUTH_USER_MODEL, verbose_name='مشتری معرفی\u200cشده')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='store.affiliatecampaign', verbose_name='کمپین')),
                ('click', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='store.affiliateclick', verbose_name='کلیک مبنا')),
            ],
            options={
                'verbose_name': 'انتساب مشتری به معرف',
                'verbose_name_plural': 'انتساب مشتریان به معرف\u200cها',
                'ordering': ['-attributed_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliatePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=store.models.generate_affiliate_code, max_length=40, unique=True, verbose_name='کد معرف')),
                ('partner_type', models.CharField(choices=[('referrer', 'معرف مشتری'), ('publisher', 'سایت یا رسانه تبلیغاتی'), ('wholesale', 'همکار خرید عمده'), ('agency', 'آژانس یا بازاریاب'), ('other', 'سایر')], default='referrer', max_length=20, verbose_name='نوع همکاری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('active', 'فعال'), ('suspended', 'تعلیق\u200cشده'), ('rejected', 'ردشده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('display_name', models.CharField(max_length=160, verbose_name='نام نمایشی همکار')),
                ('company_name', models.CharField(blank=True, max_length=180, verbose_name='نام شرکت یا وب\u200cسایت')),
                ('website', models.URLField(blank=True, verbose_name='نشانی وب\u200cسایت')),
                ('channel', models.CharField(blank=True, max_length=180, verbose_name='کانال معرفی / شبکه اجتماعی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات همکاری')),
                ('commission_type_override', models.CharField(blank=True, choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت برای هر سفارش')], max_length=20, verbose_name='نوع پورسانت اختصاصی')),
                ('commission_value_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مقدار پورسانت اختصاصی')),
                ('attribution_days_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='اعتبار اختصاصی لینک به روز')),
                ('hold_days_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='دوره انتظار اختصاصی')),
                ('minimum_payout_override', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداقل تسویه اختصاصی')),
                ('include_self_orders_override', models.BooleanField(blank=True, null=True, verbose_name='پاداش خرید شخصی اختصاصی')),
                ('sheba_number', models.CharField(blank=True, max_length=26, verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, max_length=16, verbose_name='شماره کارت')),
                ('account_holder', models.CharField(blank=True, max_length=160, verbose_name='نام صاحب حساب')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='پذیرش قوانین همکاری')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیریت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_partner', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='store.affiliatetier', verbose_name='سطح همکاری')),
            ],
            options={
                'verbose_name': 'همکار فروش و معرف',
                'verbose_name_plural': 'همکاران فروش و معرف\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت برای هر سفارش')], max_length=20, verbose_name='نوع پورسانت ثبت\u200cشده')),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='نرخ یا مبلغ ثبت\u200cشده')),
                ('basis_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ مبنای محاسبه')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ پورسانت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تحویل/تأیید'), ('approved', 'قابل تسویه'), ('requested', 'درخواست تسویه شده'), ('paid', 'پرداخت شده'), ('reversed', 'برگشت خورده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('eligible_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان قابل تأیید شدن')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان برگشت')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='store.affiliateattribution', verbose_name='انتساب مشتری')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='store.affiliatecampaign', verbose_name='کمپین')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commission', to='store.storeorder', verbose_name='سفارش')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='store.affiliatepartner', verbose_name='همکار')),
            ],
            options={
                'verbose_name': 'پورسانت همکاری',
                'verbose_name_plural': 'پورسانت\u200cهای همکاری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='affiliateclick',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='store.affiliatepartner', verbose_name='همکار'),
        ),
        migrations.AddField(
            model_name='affiliatecampaign',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='store.affiliatepartner', verbose_name='همکار'),
        ),
        migrations.AddField(
            model_name='affiliateattribution',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='store.affiliatepartner', verbose_name='معرف'),
        ),
        migrations.CreateModel(
            name='AffiliateProgramDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'داشبورد همکاری در فروش',
                'verbose_name_plural': 'داشبورد همکاری در فروش',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.affiliatepartner',),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='affiliate_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_orders', to='store.affiliatepartner', verbose_name='همکار معرف'),
        ),
        migrations.CreateModel(
            name='AffiliatePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_number', models.CharField(db_index=True, default=store.models.generate_payout_number, editable=False, max_length=40, unique=True, verbose_name='شماره تسویه')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ تسویه')),
                ('status', models.CharField(choices=[('requested', 'درخواست\u200cشده'), ('approved', 'تأیید مدیریت'), ('paid', 'پرداخت\u200cشده'), ('rejected', 'ردشده'), ('cancelled', 'لغوشده')], db_index=True, default='requested', max_length=20, verbose_name='وضعیت')),
                ('sheba_number', models.CharField(blank=True, max_length=26, verbose_name='شماره شبا هنگام درخواست')),
                ('card_number', models.CharField(blank=True, max_length=16, verbose_name='شماره کارت هنگام درخواست')),
                ('account_holder', models.CharField(blank=True, max_length=160, verbose_name='صاحب حساب')),
                ('reference_number', models.CharField(blank=True, max_length=120, verbose_name='شماره پیگیری پرداخت')),
                ('partner_note', models.TextField(blank=True, verbose_name='توضیح همکار')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیریت')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پردازش')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='store.affiliatepartner', verbose_name='همکار')),
            ],
            options={
                'verbose_name': 'درخواست تسویه همکار',
                'verbose_name_plural': 'درخواست\u200cهای تسویه همکاران',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('commission', 'اعتبار پورسانت'), ('payout', 'پرداخت تسویه'), ('reversal', 'برگشت پورسانت'), ('adjustment', 'اصلاح دستی')], db_index=True, max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ؛ مثبت بستانکار، منفی بدهکار')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='store.affiliatecommission', verbose_name='پورسانت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_ledger_actions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='store.affiliatepartner', verbose_name='همکار')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='store.affiliatepayout', verbose_name='تسویه')),
            ],
            options={
                'verbose_name': 'گردش مالی همکار',
                'verbose_name_plural': 'گردش مالی همکاران',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AffiliatePayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('commission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_item', to='store.affiliatecommission', verbose_name='پورسانت')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.affiliatepayout', verbose_name='تسویه')),
            ],
            options={
                'verbose_name': 'ردیف تسویه',
                'verbose_name_plural': 'ردیف\u200cهای تسویه',
            },
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['partner', '-created_at'], name='aff_click_partner_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='affiliatecampaign',
            constraint=models.UniqueConstraint(fields=('partner', 'slug'), name='affiliate_campaign_partner_slug_uniq'),
        ),
        migrations.RunPython(seed_affiliate_tiers, migrations.RunPython.noop),
    ]
