import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import store.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0010_material_inventory_fields"),
        ("store", "0008_affiliatecampaign_affiliatetier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintCatalogSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160, verbose_name="نام منبع")),
                ("code", models.SlugField(max_length=80, unique=True, verbose_name="کد منبع")),
                ("base_url", models.URLField(verbose_name="آدرس پایه")),
                ("allowed_domains", models.CharField(blank=True, help_text="چند دامنه را با ویرگول جدا کنید. اگر خالی باشد دامنه base_url استفاده می‌شود.", max_length=500, verbose_name="دامنه‌های مجاز")),
                ("adapter_key", models.CharField(choices=[("generic", "استخراج عمومی OpenGraph و JSON-LD"), ("custom", "آداپتور اختصاصی سایت")], default="generic", max_length=50, verbose_name="نوع استخراج")),
                ("request_headers", models.JSONField(blank=True, default=dict, verbose_name="هدرهای درخواست")),
                ("request_timeout_seconds", models.PositiveSmallIntegerField(default=20, verbose_name="مهلت درخواست به ثانیه")),
                ("respect_robots_txt", models.BooleanField(default=True, verbose_name="رعایت robots.txt")),
                ("download_preview_images", models.BooleanField(default=True, verbose_name="ذخیره تصویر پیش‌نمایش")),
                ("store_private_download_url", models.BooleanField(default=True, verbose_name="ذخیره لینک دانلود خصوصی برای ادمین")),
                ("license_note", models.TextField(blank=True, help_text="فقط منابعی را وارد کنید که اجازه استفاده، چاپ یا فروش آن‌ها را دارید.", verbose_name="یادداشت مجوز و شرایط استفاده")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="catalog_sources", to="store.category", verbose_name="دسته پیش‌فرض محصول")),
            ],
            options={"verbose_name": "منبع کاتالوگ فایل چاپ", "verbose_name_plural": "منابع کاتالوگ فایل‌های چاپ", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="FilamentPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purchase_number", models.CharField(db_index=True, default=store.models.generate_filament_purchase_number, editable=False, max_length=40, unique=True, verbose_name="شماره خرید")),
                ("supplier_name", models.CharField(blank=True, max_length=180, verbose_name="فروشنده")),
                ("invoice_number", models.CharField(blank=True, max_length=100, verbose_name="شماره فاکتور خرید")),
                ("purchased_at", models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="تاریخ خرید")),
                ("shipping_cost", models.PositiveBigIntegerField(default=0, verbose_name="هزینه حمل خرید")),
                ("other_cost", models.PositiveBigIntegerField(default=0, verbose_name="سایر هزینه‌های خرید")),
                ("status", models.CharField(choices=[("draft", "پیش‌نویس"), ("received", "وارد انبار شده"), ("cancelled", "لغو شده")], db_index=True, default="draft", max_length=20, verbose_name="وضعیت")),
                ("note", models.TextField(blank=True, verbose_name="توضیحات")),
                ("received_at", models.DateTimeField(blank=True, null=True, verbose_name="زمان ورود انبار")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="filament_purchases", to=settings.AUTH_USER_MODEL, verbose_name="ثبت‌کننده")),
            ],
            options={"verbose_name": "خرید فیلامنت", "verbose_name_plural": "خریدهای فیلامنت", "ordering": ["-purchased_at", "-id"]},
        ),
        migrations.CreateModel(
            name="ProductionJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_number", models.CharField(db_index=True, default=store.models.generate_production_job_number, editable=False, max_length=40, unique=True, verbose_name="شماره پروژه")),
                ("title", models.CharField(max_length=260, verbose_name="عنوان پروژه")),
                ("status", models.CharField(choices=[("planned", "برنامه‌ریزی"), ("printing", "در حال چاپ"), ("post_processing", "پرداخت‌کاری و تکمیل"), ("completed", "تکمیل‌شده"), ("cancelled", "لغوشده")], db_index=True, default="planned", max_length=30, verbose_name="وضعیت")),
                ("revenue_snapshot", models.PositiveBigIntegerField(default=0, verbose_name="درآمد ثبت‌شده")),
                ("tax_snapshot", models.PositiveBigIntegerField(default=0, verbose_name="مالیات ثبت‌شده")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="شروع اجرا")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="پایان اجرا")),
                ("note", models.TextField(blank=True, verbose_name="توضیحات داخلی")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_order", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="production_job", to="website.order", verbose_name="سفارش ساخت سفارشی")),
                ("store_order", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="production_job", to="store.storeorder", verbose_name="سفارش فروشگاه")),
            ],
            options={"verbose_name": "پروژه تولید و سود", "verbose_name_plural": "پروژه‌های تولید و سود", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="ImportedPrintAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_url", models.URLField(max_length=1000, verbose_name="صفحه منبع")),
                ("external_id", models.CharField(blank=True, db_index=True, max_length=160, verbose_name="شناسه در سایت منبع")),
                ("title", models.CharField(max_length=260, verbose_name="عنوان")),
                ("slug", models.SlugField(allow_unicode=True, blank=True, max_length=280, verbose_name="شناسه داخلی")),
                ("short_description", models.CharField(blank=True, max_length=500, verbose_name="توضیح کوتاه")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات کامل")),
                ("technical_specs", models.JSONField(blank=True, default=dict, verbose_name="مشخصات فنی استخراج‌شده")),
                ("tags", models.CharField(blank=True, max_length=700, verbose_name="برچسب‌ها")),
                ("author_name", models.CharField(blank=True, max_length=200, verbose_name="طراح یا ناشر")),
                ("license_name", models.CharField(blank=True, max_length=200, verbose_name="نوع مجوز")),
                ("license_url", models.URLField(blank=True, max_length=1000, verbose_name="لینک مجوز")),
                ("remote_image_url", models.URLField(blank=True, max_length=1000, verbose_name="آدرس تصویر اصلی منبع")),
                ("preview_image", models.ImageField(blank=True, null=True, upload_to="store/imported-models/previews/", verbose_name="تصویر ذخیره‌شده")),
                ("private_download_url", models.URLField(blank=True, help_text="این لینک فقط در پنل مدیریت قابل مشاهده است و در صفحات عمومی، Schema و فیدها نمایش داده نمی‌شود.", max_length=2000, verbose_name="لینک دانلود خصوصی")),
                ("file_format", models.CharField(blank=True, max_length=80, verbose_name="فرمت فایل")),
                ("source_payload", models.JSONField(blank=True, default=dict, verbose_name="داده خام استخراج")),
                ("status", models.CharField(choices=[("pending", "در انتظار بررسی"), ("reviewed", "بررسی‌شده"), ("converted", "تبدیل‌شده به محصول"), ("rejected", "ردشده")], db_index=True, default="pending", max_length=20, verbose_name="وضعیت")),
                ("admin_note", models.TextField(blank=True, verbose_name="یادداشت داخلی")),
                ("imported_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="imported_source_asset", to="store.product", verbose_name="محصول ساخته‌شده")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="store.printcatalogsource", verbose_name="منبع")),
            ],
            options={"verbose_name": "فایل آماده چاپ واردشده", "verbose_name_plural": "فایل‌های آماده چاپ واردشده", "ordering": ["-imported_at", "-id"]},
        ),
        migrations.CreateModel(
            name="FilamentPurchaseItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("brand", models.CharField(blank=True, max_length=120, verbose_name="برند")),
                ("color_name", models.CharField(blank=True, max_length=100, verbose_name="رنگ")),
                ("color_hex", models.CharField(blank=True, max_length=20, verbose_name="کد رنگ")),
                ("quantity_rolls", models.PositiveIntegerField(default=1, verbose_name="تعداد رول")),
                ("net_weight_per_roll_grams", models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name="وزن خالص هر رول به گرم")),
                ("total_purchase_amount", models.PositiveBigIntegerField(default=0, verbose_name="جمع مبلغ خرید رول‌ها")),
                ("allocated_extra_cost", models.PositiveBigIntegerField(default=0, verbose_name="سهم هزینه حمل و جانبی")),
                ("sale_price_per_gram", models.PositiveIntegerField(default=0, verbose_name="قیمت فروش هر گرم")),
                ("generated_spools", models.BooleanField(default=False, editable=False, verbose_name="رول‌ها ساخته شده‌اند")),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="filament_purchase_items", to="website.material", verbose_name="متریال")),
                ("purchase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="store.filamentpurchase", verbose_name="خرید")),
            ],
            options={"verbose_name": "ردیف خرید فیلامنت", "verbose_name_plural": "ردیف‌های خرید فیلامنت"},
        ),
        migrations.CreateModel(
            name="FilamentSpool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, default=store.models.generate_filament_spool_code, max_length=40, unique=True, verbose_name="کد رول")),
                ("brand", models.CharField(blank=True, max_length=120, verbose_name="برند")),
                ("color_name", models.CharField(blank=True, max_length=100, verbose_name="رنگ")),
                ("color_hex", models.CharField(blank=True, max_length=20, verbose_name="کد رنگ")),
                ("nominal_weight_grams", models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name="وزن اولیه خالص")),
                ("remaining_weight_grams", models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name="وزن باقی‌مانده")),
                ("tare_weight_grams", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="وزن قرقره خالی")),
                ("purchase_price", models.PositiveBigIntegerField(default=0, verbose_name="قیمت خرید این رول")),
                ("cost_per_gram_snapshot", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="قیمت تمام‌شده هر گرم")),
                ("sale_price_per_gram_snapshot", models.PositiveIntegerField(default=0, verbose_name="قیمت فروش هر گرم هنگام ورود")),
                ("status", models.CharField(choices=[("sealed", "پلمب"), ("open", "بازشده"), ("empty", "تمام‌شده"), ("quarantine", "قرنطینه"), ("archived", "بایگانی")], db_index=True, default="sealed", max_length=20, verbose_name="وضعیت")),
                ("location", models.CharField(blank=True, max_length=120, verbose_name="محل نگهداری")),
                ("purchased_at", models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="تاریخ خرید")),
                ("opened_at", models.DateTimeField(blank=True, null=True, verbose_name="زمان بازشدن")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="filament_spools", to="website.material", verbose_name="متریال")),
                ("purchase_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="spools", to="store.filamentpurchaseitem", verbose_name="ردیف خرید")),
            ],
            options={"verbose_name": "رول فیلامنت", "verbose_name_plural": "رول‌های فیلامنت", "ordering": ["material", "purchased_at", "id"]},
        ),
        migrations.CreateModel(
            name="MaterialUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("color_name", models.CharField(blank=True, max_length=100, verbose_name="رنگ")),
                ("planned_grams", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="مصرف برآوردی")),
                ("actual_grams", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="مصرف واقعی")),
                ("waste_grams", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="پرت و تست")),
                ("sale_price_per_gram_snapshot", models.PositiveIntegerField(default=0, verbose_name="قیمت فروش هر گرم")),
                ("material_charge_snapshot", models.PositiveBigIntegerField(default=0, verbose_name="فروش متریال")),
                ("cost_per_gram_snapshot", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="میانگین قیمت خرید هر گرم")),
                ("material_cost_snapshot", models.PositiveBigIntegerField(default=0, verbose_name="بهای تمام‌شده متریال")),
                ("posted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="زمان ثبت خروج انبار")),
                ("note", models.TextField(blank=True, verbose_name="توضیحات")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="material_usages", to="store.productionjob", verbose_name="پروژه")),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="production_usages", to="website.material", verbose_name="متریال")),
            ],
            options={"verbose_name": "مصرف متریال پروژه", "verbose_name_plural": "مصرف‌های متریال پروژه", "ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="ImportedPrintAssetImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("remote_url", models.URLField(blank=True, max_length=1000, verbose_name="آدرس تصویر منبع")),
                ("image", models.ImageField(blank=True, null=True, upload_to="store/imported-models/gallery/", verbose_name="تصویر ذخیره‌شده")),
                ("alt_text", models.CharField(blank=True, max_length=260, verbose_name="متن جایگزین")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="store.importedprintasset", verbose_name="فایل واردشده")),
            ],
            options={"verbose_name": "تصویر فایل واردشده", "verbose_name_plural": "تصاویر فایل‌های واردشده", "ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="PrintCatalogImportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_url", models.URLField(max_length=1000, verbose_name="صفحه هدف")),
                ("status", models.CharField(choices=[("pending", "در انتظار اجرا"), ("running", "در حال اجرا"), ("success", "موفق"), ("failed", "ناموفق")], db_index=True, default="pending", max_length=20, verbose_name="وضعیت")),
                ("log", models.TextField(blank=True, verbose_name="گزارش اجرا")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="catalog_import_jobs", to=settings.AUTH_USER_MODEL, verbose_name="ثبت‌کننده")),
                ("result_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="import_jobs", to="store.importedprintasset", verbose_name="نتیجه")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="import_jobs", to="store.printcatalogsource", verbose_name="منبع")),
            ],
            options={"verbose_name": "اجرای واردسازی کاتالوگ", "verbose_name_plural": "اجراهای واردسازی کاتالوگ", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="CostEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("design", "طراحی و مهندسی معکوس"), ("courier", "پیک"), ("shipping", "ارسال"), ("packaging", "بسته‌بندی"), ("labor", "دستمزد"), ("machine", "کارکرد دستگاه"), ("electricity", "برق و انرژی"), ("maintenance", "استهلاک و تعمیر"), ("post_processing", "پرداخت‌کاری و مونتاژ"), ("software", "نرم‌افزار و خدمات"), ("other", "سایر")], db_index=True, max_length=30, verbose_name="نوع هزینه")),
                ("description", models.CharField(max_length=300, verbose_name="شرح")),
                ("actual_cost", models.PositiveBigIntegerField(default=0, verbose_name="هزینه واقعی")),
                ("customer_charge", models.PositiveBigIntegerField(default=0, verbose_name="مبلغ دریافت‌شده از مشتری")),
                ("included_in_order_total", models.BooleanField(default=True, verbose_name="مبلغ دریافتی قبلاً در فاکتور سفارش حساب شده")),
                ("receipt", models.FileField(blank=True, null=True, upload_to="store/finance/receipts/", verbose_name="رسید یا مدرک")),
                ("incurred_at", models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="تاریخ هزینه")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cost_entries", to=settings.AUTH_USER_MODEL, verbose_name="ثبت‌کننده")),
                ("job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="cost_entries", to="store.productionjob", verbose_name="پروژه؛ برای هزینه عمومی خالی بماند")),
            ],
            options={"verbose_name": "هزینه و درآمد جانبی", "verbose_name_plural": "هزینه‌ها و درآمدهای جانبی", "ordering": ["-incurred_at", "-id"]},
        ),
        migrations.CreateModel(
            name="FilamentMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("movement_type", models.CharField(choices=[("purchase", "ورود خرید"), ("consume", "مصرف تولید"), ("waste", "پرت و تست"), ("adjustment", "اصلاح موجودی"), ("return", "بازگشت به انبار")], db_index=True, max_length=20, verbose_name="نوع گردش")),
                ("grams", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="تغییر وزن؛ خروج منفی")),
                ("balance_after", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="مانده رول")),
                ("unit_cost_snapshot", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="قیمت خرید هر گرم")),
                ("total_cost", models.PositiveBigIntegerField(default=0, verbose_name="ارزش گردش")),
                ("note", models.CharField(blank=True, max_length=400, verbose_name="توضیح")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="filament_movements", to=settings.AUTH_USER_MODEL, verbose_name="ثبت‌کننده")),
                ("job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="filament_movements", to="store.productionjob", verbose_name="پروژه")),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="filament_movements", to="website.material", verbose_name="متریال")),
                ("spool", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="store.filamentspool", verbose_name="رول")),
                ("usage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="movements", to="store.materialusage", verbose_name="مصرف پروژه")),
            ],
            options={"verbose_name": "گردش وزنی فیلامنت", "verbose_name_plural": "گردش‌های وزنی فیلامنت", "ordering": ["-created_at", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="importedprintasset",
            constraint=models.UniqueConstraint(fields=("source", "source_url"), name="unique_imported_asset_source_url"),
        ),
        migrations.AddIndex(
            model_name="filamentspool",
            index=models.Index(fields=["material", "status", "remaining_weight_grams"], name="filament_spool_stock_idx"),
        ),
        migrations.CreateModel(
            name="BusinessFinanceDashboard",
            fields=[],
            options={"verbose_name": "داشبورد انبار و سود", "verbose_name_plural": "داشبورد انبار و سود", "proxy": True, "indexes": [], "constraints": []},
            bases=("store.productionjob",),
        ),
    ]
