# Generated by Django 5.2.16 on 2026-07-21 07:37

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def seed_phase10_defaults(apps, schema_editor):
    CatalogAutomationSetting = apps.get_model("store", "CatalogAutomationSetting")
    MarketPricingSetting = apps.get_model("store", "MarketPricingSetting")
    ExchangeRateProvider = apps.get_model("store", "ExchangeRateProvider")
    CatalogSourcePolicy = apps.get_model("store", "CatalogSourcePolicy")
    CatalogSourceSchedule = apps.get_model("store", "CatalogSourceSchedule")

    CatalogAutomationSetting.objects.get_or_create(pk=1)
    MarketPricingSetting.objects.get_or_create(pk=1)
    ExchangeRateProvider.objects.get_or_create(
        code="manual-usd",
        defaults={
            "name": "نرخ دستی دلار آزاد",
            "provider_type": "manual",
            "manual_sell_rate_toman": 0,
            "priority": 100,
            "is_active": False,
        },
    )
    default_times = {
        "makerworld": datetime.time(2, 15),
        "printables": datetime.time(3, 15),
        "thingiverse": datetime.time(4, 15),
        "grabcad": datetime.time(5, 15),
    }
    for policy in CatalogSourcePolicy.objects.select_related("source"):
        CatalogSourceSchedule.objects.get_or_create(
            policy=policy,
            defaults={
                "enabled": True,
                "run_time": default_times.get(policy.source_kind, datetime.time(3, 30)),
                "requested_limit": policy.default_limit or 200,
                "sort_mode": "downloads",
                "auto_approve_commercial": True,
                "show_approved_on_homepage": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_multi_source_catalog'),
        ('website', '0011_order_intake_private_models_market_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAutomationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_enabled', models.BooleanField(default=True, help_text='اگر غیرفعال شود، اجرای زمان\u200cبندی\u200cشده منابع انجام نمی\u200cشود؛ اجرای دستی همچنان قابل ثبت است.', verbose_name='صف دریافت فعال باشد')),
                ('timezone_name', models.CharField(default='Asia/Tehran', help_text='برای سایت ایران معمولاً Asia/Tehran مناسب است.', max_length=80, verbose_name='منطقه زمانی اجرای خودکار')),
                ('process_batch_size', models.PositiveSmallIntegerField(default=1, help_text='برای جلوگیری از فشار به هاست اشتراکی مقدار ۱ یا ۲ پیشنهاد می\u200cشود.', verbose_name='تعداد Job در هر اجرای Worker')),
                ('stale_run_minutes', models.PositiveIntegerField(default=90, verbose_name='زمان تشخیص اجرای گیرکرده به دقیقه')),
                ('homepage_slider_count', models.PositiveSmallIntegerField(default=10, verbose_name='تعداد مدل در اسلایدر صفحه اول')),
                ('homepage_grid_count', models.PositiveSmallIntegerField(default=12, verbose_name='تعداد مدل در شبکه صفحه اول')),
                ('last_queue_scan_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بررسی زمان\u200cبندی')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات اتوماسیون کاتالوگ',
                'verbose_name_plural': 'تنظیمات اتوماسیون کاتالوگ',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام منبع')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='کد')),
                ('provider_type', models.CharField(choices=[('manual', 'ثبت دستی'), ('bonbast', 'Bonbast API'), ('generic_json', 'JSON API عمومی/اختصاصی')], default='manual', max_length=30, verbose_name='نوع منبع')),
                ('endpoint_url', models.URLField(blank=True, verbose_name='آدرس API')),
                ('username_env', models.CharField(blank=True, help_text='برای Bonbast مانند BONBAST_USERNAME؛ مقدار محرمانه در دیتابیس ذخیره نمی\u200cشود.', max_length=100, verbose_name='نام متغیر محیطی نام کاربری')),
                ('secret_env', models.CharField(blank=True, help_text='برای Bonbast مانند BONBAST_API_KEY.', max_length=100, verbose_name='نام متغیر محیطی کلید')),
                ('json_sell_path', models.CharField(default='usd1', help_text='نمونه: result.usd.sell یا usd1', max_length=200, verbose_name='مسیر نرخ فروش در JSON')),
                ('response_unit', models.CharField(choices=[('toman', 'تومان'), ('rial', 'ریال')], default='toman', max_length=10, verbose_name='واحد پاسخ')),
                ('multiplier', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='ضریب اصلاح')),
                ('manual_sell_rate_toman', models.PositiveBigIntegerField(default=0, verbose_name='نرخ فروش دستی دلار به تومان')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=8, verbose_name='مهلت پاسخ ثانیه')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=10, verbose_name='اولویت')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'منبع نرخ ارز',
                'verbose_name_plural': 'منابع نرخ ارز',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketPricingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='قیمت\u200cگذاری بازار فعال')),
                ('refresh_fx_minutes', models.PositiveIntegerField(default=10, verbose_name='فاصله بروزرسانی ارز به دقیقه')),
                ('refresh_bambu_hours', models.PositiveIntegerField(default=12, verbose_name='فاصله بروزرسانی Bambu Lab به ساعت')),
                ('refresh_fx_on_public_request', models.BooleanField(default=True, help_text='فقط وقتی داده قدیمی باشد و با قفل ضدتکرار؛ شکست منبع باعث اختلال صفحه مشتری نمی\u200cشود.', verbose_name='تلاش برای بروزرسانی ارز هنگام بازدید')),
                ('use_daily_high_fx', models.BooleanField(default=True, help_text='اگر نرخ صبح بیشتر از نرخ فعلی باشد، همان بیشترین نرخ روز در محاسبه استفاده می\u200cشود.', verbose_name='استفاده از بیشترین نرخ دلار روز')),
                ('default_import_cost_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='هزینه واردات و تبدیل پیش\u200cفرض درصدی')),
                ('default_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='۱۰۰ درصد یعنی دو برابر بهای محاسبه\u200cشده.', max_digits=6, verbose_name='حاشیه فروش پیش\u200cفرض درصدی')),
                ('price_rounding_toman', models.PositiveIntegerField(default=100, verbose_name='گردکردن قیمت هر گرم به تومان')),
                ('last_fx_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('last_bambu_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, verbose_name='آخرین خطا')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات قیمت\u200cگذاری بازار',
                'verbose_name_plural': 'تنظیمات قیمت\u200cگذاری بازار',
            },
        ),
        migrations.CreateModel(
            name='CatalogAssetPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='اگر خالی باشد، بر اساس نام مدل و سفارش چاپ سه\u200cبعدی ساخته می\u200cشود.', max_length=180, verbose_name='عنوان سئو')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='توضیحات متا')),
                ('image_alt_text', models.CharField(blank=True, max_length=260, verbose_name='متن جایگزین تصویر')),
                ('show_on_homepage', models.BooleanField(db_index=True, default=False, verbose_name='نمایش در صفحه اول')),
                ('homepage_priority', models.PositiveIntegerField(db_index=True, default=100, verbose_name='اولویت صفحه اول')),
                ('first_published_at', models.DateTimeField(blank=True, null=True, verbose_name='اولین انتشار')),
                ('last_public_refresh_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بروزرسانی عمومی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metrics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='store.catalogassetmetrics', verbose_name='مدل خارجی')),
            ],
            options={
                'verbose_name': 'انتشار و سئوی مدل خارجی',
                'verbose_name_plural': 'انتشار و سئوی مدل\u200cهای خارجی',
                'ordering': ['homepage_priority', '-metrics__downloads_count'],
            },
        ),
        migrations.CreateModel(
            name='CatalogQueuedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', 'دستی از پنل'), ('scheduled', 'زمان\u200cبندی\u200cشده'), ('command', 'خط فرمان')], db_index=True, default='manual', max_length=20, verbose_name='نوع اجرا')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان برنامه\u200cریزی\u200cشده')),
                ('hydrate_files', models.BooleanField(default=False, verbose_name='دریافت جزئیات فایل')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان دریافت توسط Worker')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_job', to='store.catalogsyncrun', verbose_name='اجرای کاتالوگ')),
            ],
            options={
                'verbose_name': 'Job صف همگام\u200cسازی',
                'verbose_name_plural': 'Jobهای صف همگام\u200cسازی',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSourceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=False, verbose_name='اجرای روزانه فعال')),
                ('run_time', models.TimeField(default=datetime.time(3, 30), help_text='زمان بر اساس منطقه زمانی تنظیم\u200cشده در اتوماسیون تفسیر می\u200cشود.', verbose_name='ساعت اجرای روزانه')),
                ('weekdays', models.CharField(default='0,1,2,3,4,5,6', help_text='روزهای هفته با عدد 0 تا 6 و جداشده با ویرگول؛ 0 دوشنبه و 6 یکشنبه است. برای هر روز: 0,1,2,3,4,5,6', max_length=30, verbose_name='روزهای اجرا')),
                ('sort_mode', models.CharField(choices=[('downloads', 'بیشترین دانلود'), ('likes', 'بیشترین لایک'), ('views', 'بیشترین بازدید'), ('trending', 'ترند'), ('newest', 'جدیدترین')], default='downloads', max_length=20, verbose_name='مرتب\u200cسازی دریافت')),
                ('requested_limit', models.PositiveIntegerField(default=200, help_text='این مقدار از سقف تعیین\u200cشده در سیاست منبع بیشتر نمی\u200cشود.', verbose_name='تعداد مدل در هر اجرا')),
                ('hydrate_files', models.BooleanField(default=False, help_text='برای Thingiverse نیازمند API رسمی است. فایل\u200cها برای مشتری قابل دانلود نیستند.', verbose_name='دریافت جزئیات فایل\u200cها')),
                ('auto_approve_commercial', models.BooleanField(default=False, help_text='فقط وقتی Adapter به\u200cطور صریح اجازه فروش چاپ فیزیکی را تشخیص دهد اعمال می\u200cشود.', verbose_name='تأیید خودکار مجوزهای تجاری صریح')),
                ('cache_images_after_approval', models.BooleanField(default=True, verbose_name='ذخیره تصویر محلی پس از تأیید')),
                ('show_approved_on_homepage', models.BooleanField(default=True, verbose_name='نمایش مدل\u200cهای تأییدشده در صفحه اول')),
                ('last_queued_on', models.DateField(blank=True, null=True, verbose_name='آخرین روز صف\u200cشدن')),
                ('last_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اجرای موفق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='store.catalogsourcepolicy', verbose_name='سیاست منبع')),
            ],
            options={
                'verbose_name': 'زمان\u200cبندی دریافت منبع',
                'verbose_name_plural': 'زمان\u200cبندی دریافت منابع',
            },
        ),
        migrations.CreateModel(
            name='CatalogAutomationDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'داشبورد همگام\u200cسازی و قیمت زنده',
                'verbose_name_plural': 'داشبورد همگام\u200cسازی و قیمت زنده',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.catalogsourceschedule',),
        ),
        migrations.CreateModel(
            name='MaterialMarketPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bambu_usd_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت دلاری Bambu')),
                ('fx_current_toman', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='نرخ فعلی دلار')),
                ('fx_daily_high_toman', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='بیشترین نرخ دلار روز')),
                ('cost_per_gram_toman', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='بهای محاسباتی هر گرم')),
                ('sale_per_gram_toman', models.PositiveBigIntegerField(verbose_name='قیمت فروش هر گرم')),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_price_snapshots', to='website.material', verbose_name='متریال')),
            ],
            options={
                'verbose_name': 'تاریخچه قیمت متریال',
                'verbose_name_plural': 'تاریخچه قیمت متریال\u200cها',
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(db_index=True, default='USD', max_length=10)),
                ('sell_rate_toman', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='نرخ فروش به تومان')),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('local_date', models.DateField(db_index=True, verbose_name='تاریخ محلی')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='store.exchangerateprovider', verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'نمونه نرخ ارز',
                'verbose_name_plural': 'تاریخچه نرخ ارز',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['currency', 'local_date', '-sell_rate_toman'], name='store_fx_day_high_idx')],
            },
        ),
        migrations.RunPython(seed_phase10_defaults, migrations.RunPython.noop),
    ]
