# Generated by Django 5.2.16 on 2026-07-21 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models




def seed_phase11_sources(apps, schema_editor):
    ExchangeRateProvider = apps.get_model("store", "ExchangeRateProvider")
    MarketPricingSetting = apps.get_model("store", "MarketPricingSetting")
    setting, _ = MarketPricingSetting.objects.get_or_create(pk=1)
    setting.tgju_profile_url = "https://www.tgju.org/profile/price_dollar_rl"
    setting.bambu_collection_url = "https://us.store.bambulab.com/collections/bambu-lab-3d-printer-filament?from=home_web_top_navigation"
    setting.save(update_fields=["tgju_profile_url", "bambu_collection_url"])
    ExchangeRateProvider.objects.update_or_create(
        code="tgju-dollar",
        defaults={
            "name": "دلار آزاد TGJU",
            "provider_type": "tgju_html",
            "endpoint_url": "https://www.tgju.org/profile/price_dollar_rl",
            "response_unit": "rial",
            "multiplier": 1,
            "timeout_seconds": 15,
            "priority": 1,
            "is_active": True,
        },
    )

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_phase10_automation_pricing_homepage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BambuFilamentCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='شناسه Bambu')),
                ('handle', models.SlugField(max_length=220, unique=True, verbose_name='Handle محصول')),
                ('title', models.CharField(max_length=220, verbose_name='نام فیلامنت')),
                ('product_url', models.URLField(max_length=1000, verbose_name='لینک رسمی محصول')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='تصویر رسمی')),
                ('vendor', models.CharField(blank=True, max_length=120, verbose_name='برند')),
                ('product_type', models.CharField(blank=True, max_length=120, verbose_name='نوع محصول')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cها')),
                ('min_price_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='کمترین قیمت دلار')),
                ('max_price_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='بیشترین قیمت دلار')),
                ('conservative_price_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت محافظه\u200cکارانه')),
                ('available', models.BooleanField(db_index=True, default=True, verbose_name='موجود')),
                ('variants', models.JSONField(blank=True, default=list, verbose_name='تنوع\u200cها و قیمت\u200cها')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='داده خام')),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='آخرین مشاهده')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قیمت فیلامنت Bambu',
                'verbose_name_plural': 'کاتالوگ قیمت فیلامنت\u200cهای Bambu Lab',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='marketpricingsetting',
            name='bambu_collection_url',
            field=models.URLField(default='https://us.store.bambulab.com/collections/bambu-lab-3d-printer-filament?from=home_web_top_navigation', help_text='فهرست رسمی فروشگاه آمریکا؛ قیمت تنوع\u200cها به دلار دریافت می\u200cشود.', verbose_name='مجموعه فیلامنت Bambu Lab'),
        ),
        migrations.AddField(
            model_name='marketpricingsetting',
            name='last_bambu_catalog_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین همگام\u200cسازی مجموعه Bambu'),
        ),
        migrations.AddField(
            model_name='marketpricingsetting',
            name='source_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='مهلت اتصال به منابع به ثانیه'),
        ),
        migrations.AddField(
            model_name='marketpricingsetting',
            name='tgju_profile_url',
            field=models.URLField(default='https://www.tgju.org/profile/price_dollar_rl', help_text='صفحه عمومی دلار آزاد؛ نرخ فعلی و بالاترین نرخ روز از همین صفحه استخراج می\u200cشود.', verbose_name='صفحه نرخ دلار TGJU'),
        ),
        migrations.AlterField(
            model_name='exchangerateprovider',
            name='endpoint_url',
            field=models.URLField(blank=True, verbose_name='آدرس منبع / API'),
        ),
        migrations.AlterField(
            model_name='exchangerateprovider',
            name='provider_type',
            field=models.CharField(choices=[('manual', 'ثبت دستی'), ('bonbast', 'Bonbast API'), ('generic_json', 'JSON API عمومی/اختصاصی'), ('tgju_html', 'صفحه عمومی TGJU')], default='manual', max_length=30, verbose_name='نوع منبع'),
        ),
        migrations.CreateModel(
            name='ExternalSourceFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(choices=[('tgju', 'TGJU نرخ دلار'), ('bambu', 'Bambu Lab'), ('makerworld', 'MakerWorld'), ('printables', 'Printables'), ('thingiverse', 'Thingiverse'), ('grabcad', 'GrabCAD'), ('fx', 'سایر منابع ارز')], db_index=True, max_length=30, verbose_name='منبع')),
                ('action', models.CharField(choices=[('test', 'تست اتصال و پارسر'), ('fetch_rate', 'دریافت نرخ'), ('sync', 'همگام\u200cسازی'), ('catalog_probe', 'تست دریافت مدل')], db_index=True, max_length=30, verbose_name='عملیات')),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('running', 'در حال اجرا'), ('success', 'موفق'), ('partial', 'نسبی'), ('failed', 'ناموفق')], db_index=True, default='queued', max_length=20, verbose_name='وضعیت')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت درصدی')),
                ('current_stage', models.CharField(blank=True, max_length=160, verbose_name='مرحله فعلی')),
                ('message', models.TextField(blank=True, verbose_name='پیام نتیجه')),
                ('error', models.TextField(blank=True, verbose_name='جزئیات خطا')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP Status')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='مدت اجرا میلی\u200cثانیه')),
                ('records_found', models.PositiveIntegerField(default=0, verbose_name='رکورد پیدا شده')),
                ('records_saved', models.PositiveIntegerField(default=0, verbose_name='رکورد جدید')),
                ('records_updated', models.PositiveIntegerField(default=0, verbose_name='رکورد بروزشده')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='رکورد ناموفق')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='خلاصه فنی')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_source_logs', to=settings.AUTH_USER_MODEL, verbose_name='اجراکننده')),
            ],
            options={
                'verbose_name': 'گزارش دریافت منبع',
                'verbose_name_plural': 'گزارش\u200cهای دریافت و تست منابع',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(seed_phase11_sources, migrations.RunPython.noop),
    ]
