# Generated by Django 6.0.7 on 2026-07-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_phase26_realtime_manual_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogsourcepolicy',
            name='public_reference_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='در صورت فعال\u200cبودن، نام، تصاویر، مشخصات و لینک صفحه منبع حتی بدون فایل مستقیم یا مجوز فروش به\u200cصورت مرجع نمایش داده می\u200cشود. لینک فایل خصوصی هرگز عمومی نمی\u200cشود.', verbose_name='نمایش مرجع عمومی'),
        ),
    ]
