# Generated by Django 6.0.6 on 2026-07-05 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IndustryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=150, verbose_name='صنعت')),
                ('recommended_materials', models.CharField(max_length=255, verbose_name='متریال مناسب')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'پیشنهاد متریال برای صنعت',
                'verbose_name_plural': 'پیشنهاد متریال برای صنایع',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='متریال')),
                ('strength', models.PositiveSmallIntegerField(default=0, verbose_name='استحکام')),
                ('heat_resistance', models.PositiveSmallIntegerField(default=0, verbose_name='مقاومت حرارتی')),
                ('flexibility', models.PositiveSmallIntegerField(default=0, verbose_name='انعطاف')),
                ('chemical_resistance', models.PositiveSmallIntegerField(default=0, verbose_name='مقاومت شیمیایی')),
                ('printability', models.PositiveSmallIntegerField(default=0, verbose_name='سختی/سهولت چاپ')),
                ('main_usage', models.CharField(max_length=255, verbose_name='کاربردهای اصلی')),
                ('sample_parts', models.TextField(verbose_name='نمونه قطعات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'متریال',
                'verbose_name_plural': 'متریال\u200cها',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('description', models.TextField(verbose_name='توضیحات سفارش')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('priced', 'قیمت\u200cگذاری شده'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده'), ('cancelled', 'لغو شده')], default='new', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150, verbose_name='قطعه')),
                ('best_material', models.CharField(max_length=150, verbose_name='بهترین متریال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'پیشنهاد متریال برای قطعه',
                'verbose_name_plural': 'پیشنهاد متریال برای قطعات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نمونه\u200cکار')),
                ('category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='متریال')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='صنعت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='تصویر')),
                ('project_duration', models.CharField(blank=True, max_length=100, verbose_name='مدت انجام')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'نمونه\u200cکار',
                'verbose_name_plural': 'نمونه\u200cکارها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('base_price', models.PositiveIntegerField(default=0, verbose_name='قیمت پایه به تومان')),
                ('delivery_time', models.CharField(max_length=100, verbose_name='زمان آماده\u200cسازی')),
                ('materials', models.CharField(max_length=255, verbose_name='متریال\u200cهای قابل انتخاب')),
                ('colors', models.CharField(max_length=255, verbose_name='رنگ\u200cبندی')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محصول سفارشی',
                'verbose_name_plural': 'محصولات سفارشی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='3DprintHub.ir', max_length=100, verbose_name='نام برند')),
                ('hero_title', models.CharField(default='طراحی، چاپ سه\u200cبعدی و مهندسی معکوس قطعات صنعتی', max_length=255, verbose_name='عنوان اصلی سایت')),
                ('hero_subtitle', models.TextField(default='از نمونه\u200cسازی اولیه تا ساخت قطعات کاربردی صنعتی با متریال\u200cهای مهندسی.', verbose_name='توضیح اصلی سایت')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='شماره تماس')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='شماره واتساپ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('instagram', models.URLField(blank=True, verbose_name='لینک اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='لینک تلگرام')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('working_hours', models.CharField(blank=True, max_length=150, verbose_name='ساعت کاری')),
                ('map_embed_url', models.TextField(blank=True, verbose_name='کد iframe نقشه یا لینک نقشه')),
                ('meta_title', models.CharField(default='3DprintHub.ir | طراحی، چاپ سه\u200cبعدی و مهندسی معکوس قطعات صنعتی', max_length=255, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(default='خدمات طراحی سه\u200cبعدی، چاپ سه\u200cبعدی صنعتی، مهندسی معکوس و ساخت قطعات سفارشی با متریال\u200cهای مهندسی.', verbose_name='توضیحات سئو')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='نام مشتری')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='نام شرکت')),
                ('text', models.TextField(verbose_name='متن رضایت')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رضایت مشتری',
                'verbose_name_plural': 'رضایت مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/', verbose_name='تصویر سفارش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تصویر سفارش',
                'verbose_name_plural': 'تصاویر سفارش',
            },
        ),
    ]
