# Generated by Django 6.0.6 on 2026-07-05 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price_per_kg',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت هر کیلوگرم به تومان'),
        ),
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='رنگ موردنظر'),
        ),
        migrations.AddField(
            model_name='order',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='website.material', verbose_name='متریال انتخابی'),
        ),
        migrations.AddField(
            model_name='order',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن عمومی سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('3d_print', 'چاپ سه\u200cبعدی'), ('design', 'طراحی سه\u200cبعدی'), ('reverse_engineering', 'مهندسی معکوس'), ('prototype', 'نمونه\u200cسازی'), ('custom_part', 'ساخت قطعه سفارشی')], default='3d_print', max_length=50, verbose_name='نوع خدمت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='accent_color',
            field=models.CharField(default='#22C55E', max_length=20, verbose_name='رنگ تأکیدی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_color',
            field=models.CharField(default='#38BDF8', max_length=20, verbose_name='رنگ اصلی برند'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='secondary_color',
            field=models.CharField(default='#0F172A', max_length=20, verbose_name='رنگ دوم برند'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('quoted', 'پیش\u200cفاکتور صادر شده'), ('accepted', 'تأیید شده توسط مشتری'), ('paid', 'پرداخت شده'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده'), ('cancelled', 'لغو شده')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='وزن قطعه به گرم')),
                ('print_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان چاپ به دقیقه')),
                ('machine_hourly_rate', models.PositiveIntegerField(default=0, verbose_name='هزینه ساعتی دستگاه به تومان')),
                ('labor_fee', models.PositiveIntegerField(default=0, verbose_name='دستمزد ساخت/اپراتوری به تومان')),
                ('design_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه طراحی یا مهندسی معکوس به تومان')),
                ('post_processing_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه پرداخت\u200cکاری/مونتاژ به تومان')),
                ('shipping_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال به تومان')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='تخفیف به تومان')),
                ('admin_note', models.TextField(blank=True, verbose_name='توضیحات داخلی')),
                ('customer_note', models.TextField(blank=True, verbose_name='توضیحات قابل نمایش به مشتری')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده برای مشتری'), ('accepted', 'تأیید شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='draft', max_length=20, verbose_name='وضعیت پیش\u200cفاکتور')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='اعتبار پیش\u200cفاکتور تا تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.material', verbose_name='متریال نهایی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='website.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پیش\u200cفاکتور',
                'verbose_name_plural': 'پیش\u200cفاکتورها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ به تومان')),
                ('method', models.CharField(choices=[('gateway', 'درگاه پرداخت'), ('bank_transfer', 'کارت به کارت / واریز دستی')], default='gateway', max_length=30, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('authority', models.CharField(blank=True, max_length=255, verbose_name='Authority درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=255, verbose_name='کد پیگیری پرداخت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='تصویر رسید پرداخت دستی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='website.quote', verbose_name='پیش\u200cفاکتور')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
