# Generated by Django 6.0.6 on 2026-07-05 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_order_customer_customerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='price_tolerance_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تلورانس قیمت درصدی'),
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], default=5, verbose_name='امتیاز')),
                ('comment', models.TextField(verbose_name='نظر مشتری')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده توسط ادمین')),
                ('display_on_site', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='website.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'نظر مشتری روی سفارش',
                'verbose_name_plural': 'نظرات مشتریان روی سفارشات',
                'ordering': ['-created_at'],
            },
        ),
    ]
