# Generated by Django 5.2.15 on 2026-07-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_quote_price_tolerance_percent_orderreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIndustryGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=120, unique=True, verbose_name='صنعت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('recommended_materials', models.ManyToManyField(blank=True, related_name='industry_guides', to='website.material', verbose_name='متریال\u200cهای پیشنهادی')),
            ],
            options={
                'verbose_name': 'راهنمای متریال بر اساس صنعت',
                'verbose_name_plural': 'راهنمای متریال بر اساس صنایع',
                'ordering': ['sort_order', 'industry'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPartGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150, unique=True, verbose_name='نام قطعه')),
                ('reason', models.TextField(blank=True, verbose_name='دلیل پیشنهاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('alternative_materials', models.ManyToManyField(blank=True, related_name='alternative_for_parts', to='website.material', verbose_name='متریال\u200cهای جایگزین')),
                ('best_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for_parts', to='website.material', verbose_name='بهترین متریال')),
            ],
            options={
                'verbose_name': 'راهنمای متریال بر اساس قطعه',
                'verbose_name_plural': 'راهنمای متریال بر اساس قطعات',
                'ordering': ['sort_order', 'part_name'],
            },
        ),
    ]
