# Generated by Django 5.2.15 on 2026-07-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_materialindustryguide_materialpartguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialpartguide',
            name='alternative_materials',
        ),
        migrations.RemoveField(
            model_name='materialpartguide',
            name='best_material',
        ),
        migrations.DeleteModel(
            name='MaterialIndustryGuide',
        ),
        migrations.DeleteModel(
            name='MaterialPartGuide',
        ),
    ]
